### ISSUE TITLE
Logging not set up if container initialization fails

### ISSUE THREAD

**Issue by MarvinNorway** [cleancodelabs/Serilog.Extensions.Autofac.DependencyInjection#1]
I have a singleton in my container. The registration process looks like this:

```csharp
            var containerBuilder = new ContainerBuilder();

            var loggerConfiguration = new LoggerConfiguration()
                                                      .WriteTo.Console()
                                                      .ReadFrom.AppSettings();

            containerBuilder.RegisterSerilog(loggerConfiguration);

            containerBuilder.RegisterInstance(CreateSingleton());

            // [... more registration ...]

            IContainer container = containerBuilder.Build();
```

The problem is that if the `CreateSingleton()` call throws an exception, logging won't be set up yet as the `SerilogModule` hasn't been loaded yet.

But if I manually create the logger (`Log.Logger = loggerConfiguration.CreateLogger();`) before building the container and `CreateSingleton()` doesn't fail, then I get an exception telling me that `CreateLogger()` has been called twice (once explicitly by my code, and another time by the `SerilogModule`), which is not allowed.

This would be easy to solve by simply moving the `CreateLogger()` call outside the `SerilogModule`, i.e. directly into the `RegisterSerilog` method.

Is this something you would consider?

At the moment, I have to resort to this ugly workaround:

```csharp
try
{
    containerBuilder.RegisterInstance(CreateSingleton());
}
catch
{
    Log.Logger = loggerConfiguration.CreateLogger();
    throw;
}
```

Thanks.

**Comment by alsami** [comment]
Hey Marvin,

thanks for the issue! I'll apply the suggest fix.

**Comment by MarvinNorway** [comment]
Thank you!

**Comment by alsami** [comment]
Package has been [published ](https://travis-ci.com/cleancodelabs/Serilog.Extensions.Autofac.DependencyInjection/jobs/242627606) just now and should be available on nuget soon.
